### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by TanyaDvorkina** [edgraham/BinSanity#14]
Hi,

I am trying to run Binsanity on a large number of contigs (about 130 000) and getting a segmentation fault. Could you please help me? Please find printed log below:
~/binsanity$ Binsanity -f ./synth -l samples_splits_f.fasta -c profiles.in

        -------------------------------------------------------
                          Running Binsanity

                    ---Computing Coverage Array ---
        -------------------------------------------------------

Preference: -3
Maximum Iterations: 4000
Convergence Iterations: 400
Contig Cut-Off: 1000
Damping Factor: 0.95
Coverage File: profiles.in
Fasta File: samples_splits_f.fasta
Output directory: BINSANITY-RESULTS
(133693, 8)

        -------------------------------------------------------
                      ---Clustering Contigs---
        -------------------------------------------------------

Segmentation fault

The same command works on subsample (about 20 000 contigs)

**Comment by edgraham** [comment]
Hello,

This error typically arises when your too low on memory for Binsanity to proceed. Unfortuantely due to the nature of the algorithm there are some high memory constraints. Typically our lab caps input at 100,000 contigs when using `Binsanity`. 

I recommend you try running `Binsanity-lc. What this does is it subsamples your contigs using coverage using a less memory intensive method and then implements Affinity Propagation on those subsets. If you want to mimic the command you are running now use this command:

`Binsanity-lc -f ./synth -l samples_splits_f.fasta -c profiles.in` 

Depending on how many threads you can open up at once I'd also recommend using the `--threads` flag with `Binsanity-lc` for the appropriate number available as it will speed up the K-means subsampling step and refinement. 

Let me know if you have any questions!

-- Elaina

**Comment by TanyaDvorkina** [comment]
Thank you, Elaina!

I run Binsanity-lc command and it worked.

**Comment by edgraham** [comment]
Your very welcome, glad to hear it worked!

**Comment by TanyaDvorkina** [comment]
Hi Elaina!

Binsanity-lc made initial clustering, but now it is working on CheckM step for too long.
I decided to run it on a toy dataset (~ 600 contigs) with command

> Binsanity-lc -f ./ -l samples_frags.fasta -c depth_concoct.txt -o toy_result --threads 33

to test CheckM on a small data and it is working for 12 hours already, is it Ok?

Thanks,
Tatiana

**Comment by edgraham** [comment]
Hi Tatiana,

I am looking at this right now. I'll run a couple of test datasets to try
and locate the issue.

In the mean time can you send me the version info for your install of
Binsanity.

Regards,
Elaina

**Comment by TanyaDvorkina** [comment]
Hi Elaina,

Sorry, it is not the latest one: Binsanity v0.2.5.9 
I installed it to miniconda environment with pip install. I'll try to update it.

Thanks,
Tatiana
