### ISSUE TITLE
tests?

### ISSUE THREAD

**Issue by wwood** [edgraham/BinSanity#18]
Hi,
Is there any tests available? I've managed to install it but am not sure on certain things e.g. is bedtools 2.17 really required or is 2.18 OK?
Thanks, ben

**Comment by edgraham** [comment]
Hi Ben,

2.18 should be fine. I don’t have a full test for the Binsanity-profile.
Bam files can get very large and GitHub has a size limit on file uploads so
I chose not to download an example :/

The versions are just a statement that when I last updated the script
that’s what we were running on our server, and in most cases as long as you
have that version or greater you should be alright. If you get an error let
me know though and I will look into it.

Regards,
Elaina

On Oct 13, 2017, at 11:19 PM, Ben J Woodcroft <notifications@github.com>
wrote:

Hi,
Is there any tests available? I've managed to install it but am not sure on
certain things e.g. is bedtools 2.17 really required or is 2.18 OK?
Thanks, ben

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/edgraham/BinSanity/issues/18>, or mute the thread
