### ISSUE TITLE
problem with profile "OSError: [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by camillaln** [edgraham/BinSanity#19]
Hi,

I am trying to run Binsanity-profile, but I am getting an error. I have mapped reads using BBmap and the BBmap folder in my commandline contains the sorted file DG074megahit_sorted.bam and the index DG074megahit_sorted.bam.bai

My command line is:
nohup /usr/local/bin/Binsanity-profile -i /groups/edwards/camilla/Kart_assemblies/megahit/DG074_simplified_final.contigs.fa -s /groups/edwards/camilla/Kart_assemblies/megahit/Binsanity/DG074/BBmap/ --ids /groups/edwards/camilla/Kart_assemblies/megahit/Binsanity/DG074/DG074.id.txt -c /groups/edwards/camilla/Kart_assemblies/megahit/Binsanity/DG074/DG074.cov &

I get the following error:
 ******************************************************
                    Contigs formated to generate counts
        ******************************************************
        
Traceback (most recent call last):
  File "/usr/local/bin/Binsanity-profile", line 166, in <module>
    feature_counts(args.inputMapLoc,args.outDirectory,args.Threads)
  File "/usr/local/bin/Binsanity-profile", line 28, in feature_counts
    subprocess.call(["featureCounts","-M","-O", "-F", "SAF","-T",str(threads),"-a", os.path.join(outputdir,str(outname)+".saf"),"-o", os.path.join(outputdir,str(outname)+".readcounts"),str(mapfile_fil
e)],stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Could you help me spot my error.
Thanks,
Camilla

**Comment by edgraham** [comment]
Hi Camilla,

I believe the issue is with how you called the output for the coverage
file. try running it like this and let me know if you get the same error.

nohup /usr/local/bin/Binsanity-profile -i /groups/edwards/camilla/Kart_
assemblies/megahit/DG074_simplified_final.contigs.fa -s
/groups/edwards/camilla/Kart_assemblies/megahit/Binsanity/DG074/BBmap/
--ids /groups/edwards/camilla/Kart_assemblies/megahit/Binsanity/DG074/DG074.id.txt
-c DG074/DG074.cov -o  /groups/edwards/camilla/Kart_
assemblies/megahit/Binsanity/ &

I think whats happening is that because I added the `-o` so the user can
specify an output directory it is trying to combine the default directory
(Which I set as the working directory) and the specified output file
therefor rather than opening your output file in
 /groups/edwards/camilla/Kart_assemblies/megahit/Binsanity/ it is trying to
open one in `. /groups/edwards/camilla/Kart_assemblies/megahit/Binsanity/`
which wouldn't exist.

Regards,
Elaina

**Comment by camillaln** [comment]
Thanks for getting back to me Elaina.

I tried your command line and got the same error. So I tried moving all my files to the same directory did:
/usr/local/bin/Binsanity-profile -i DG074_simplified_final.contigs.fa -s BBmap/ --ids DG074.id.txt -c DG074.cov &

and still the same error:
        ******************************************************
                    Contigs formated to generate counts
        ******************************************************
        
Traceback (most recent call last):
  File "/usr/local/bin/Binsanity-profile", line 166, in <module>
    feature_counts(args.inputMapLoc,args.outDirectory,args.Threads)
  File "/usr/local/bin/Binsanity-profile", line 28, in feature_counts
    subprocess.call(["featureCounts","-M","-O", "-F", "SAF","-T",str(threads),"-a", os.path.join(outputdir,str(outname)+".saf"),"-o", os.path.join(outputdir,str(outname)+".readcounts"),str(mapfile_fil
e)],stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by edgraham** [comment]
Hi Camilla,

So it seems there must be an issue somewhere with either a file name or
directory name. Are the `.saf` files being produced? Thats where it seems
to be failing is when looking for those files.

Regards,
Elaina

**Comment by camillaln** [comment]
Yes. The a .saf file is produced.
Its put into the same directory as where I am running from.
Camilla

**Comment by edgraham** [comment]
Hi Camilla,

I am at a loss at what this may be because I can't seem to replicate the
error.

So considering that lets check a couple things:

1. Are you running the most uptodate version of Binsanity? (should be
v0.2.6.1)
2. Is your featurCounts installation working properly? Try testing feature
counts outside of Binsanity-profile, does it produce the correct files? To
try that run:

featureCounts -M -O -F SAF -T 2 -a [saf file name] -o [output file name
(should end in .readcounts)]  [BAM FILE TO BE PROFILED]

If both of those are working fine then I'll have to delve into this deeper
because I have yet to be able to replicate the same error and its been
running fine on all my test datasets.

reagrds,
Elaina

**Comment by camillaln** [comment]
I did not do the installation, but I think you are right, the featurCounts does not look to be working. I will check with the system manager if he can sort that out for me! Thank you so much for your help with this. 
Camilla

**Comment by edgraham** [comment]
Hi Camilla,

I’m glad we pinpointed one potential cause, let me know if installing featureCounts fixes it. Here’s the link to the subread package information it’s contained in if you need it!
http://subread.sourceforge.net/


Regards,
Elaina
