### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by selffi** [edgraham/BinSanity#23]
I am trying to run the test dats in binsanity. But I am getting the following error. How to rectify this
Traceback (most recent call last):
  File "/usr/local/bin/Binsanity", line 182, in <module>
    val1, val2 = cov_array((get_cov_data(args.inputCovFile)), args.inputContigFiles, args.fastafile,args.ContigSize)
  File "/usr/local/bin/Binsanity", line 21, in get_cov_data
    all_cov_data[cov_data[0]] = cov_data
IndexError: list index out of range

**Comment by edgraham** [comment]
Hello,

This is a repeating error I have seen with others but I haven't yet been
able to determine what is causing this because it does not repeat the error
on my own set-up :/ What version of all of the dependencies are your
running? I'll see if I can correlate the error with something so I can work
to fix the issue.

Regards,
Elaina Graham

**Comment by selffi** [comment]
I am using the following version of the dependecies
python 2.7
bedtools v2.21.0
Bowtie2 2.2.4
numpy 1.13.3
scipy 1.0.0
The scikit-learn version is 0.19.1.
Biopython 1.70
pandas 0.21.1
featureCounts: subread 1.6.0
hmmer-3.1
CheckM v1.0.9

**Comment by edgraham** [comment]
Thanks! I will get on this ASAP to see if I can pinpoint the issue.

**Comment by edgraham** [comment]
The newest version of BinSanity shouldn't throw this error. Let me know though it you continue to see it though.

**Comment by kgweiss** [comment]
I just setup BinSanity today and am seeing this issue again with the sample data:

Traceback (most recent call last):
  File "/home/kgweiss/.local/bin/Binsanity", line 200, in <module>
    val1, val2 = cov_array((get_cov_data(args.inputCovFile)), args.inputContigFiles, args.fastafile,args.ContigSize)
  File "/home/kgweiss/.local/bin/Binsanity", line 28, in get_cov_data
    all_cov_data[cov_data[0]] = cov_data
IndexError: list index out of range

Dependencies list:
python 2.7.14
bedtools2 v2.25.0
Bowtie2 2.2.9
numpy 1.11.1
scipy 1.1.0
The scikit-learn version is 0.19.1.
Biopython 1.68
pandas 0.23.1
featureCounts: subread 1.6.1
hmmer-3.1b2
checkm-genome  1.0.13

Please advise.

Thanks,
Ken

**Comment by edgraham** [comment]
Hi Ken,

All your dependencies look solid so I don't think thats the issue, but I'll
run through and double check. Some imediate things you can look at which I
have had some issues with before is that the example file is still actually
tab delimited (for some reason sometimes I pull that file down from github
and it isn't tab delimited anymore which poses an issue). Second  thing to
check is that your identifying the right location for the coverage profile.
That error implies that it is trying to read the coverage profile and
populate a dictionary with the data but is failing leading to an empty
dictionary.

If those two things don't work then it is likely due to a dependency that
I'll hopefully be able to identify quickly.

-Elaina

**Comment by kgweiss** [comment]
Elaina,

Thanks for getting back to me so quickly. I will spend some more time working on this issue today.

Cheers,
Ken

**Comment by kgweiss** [comment]
Elaina,

Looks like I had an ID 10 T problem with the data files. It is working now.

Thanks,
Ken

**Comment by edgraham** [comment]
Great, glad to hear everything is up and running!

Please let us know if you run into any other issues.
