### ISSUE TITLE
Does Binsanity_lc continue from checkpoints?

### ISSUE THREAD

**Issue by jvollme** [edgraham/BinSanity#31]
Since I have a huge metagenome assembly, i had to use binsanity_lc or risk running out of Memory. 

The binsanity_lc run seemed to go fine, but took longer than the three days max-runtime allowed on our institutes servers. So it was killed before it could finish.

Is there a way to call binsanity_lc so that it picks up at the latest checkpoint instead of restarting from the absolute beginning? Or do I have to restart from scratch?

**Comment by jarrodscott** [comment]
Hi. Was a solution ever devised for this question? Or is the suggested workaround still the best way forward?

**Comment by edgraham** [comment]
Hi Jarrod,

Unfortunately I haven’t had time to code a new work around for this as I was focused on transitioning everything to python3. It turned into a bit of a coding nightmare to tackle so was tabled until the the new year!

Does it seem to cancel mid-run often for you when your implementing?

-Elaina

**Comment by jarrodscott** [comment]
Hi Elaina, 

Thank you for your response and no problem at all. I am sure the transition was not trivial!

The last time it failed somewhere in the checkm step. I certainly do not mind running everything as individual steps rather than the wf. I just was not really sure how to do that. Is there an existing protocol for that? If not,  can take a crack at writing a little protocol on how to do this. Thanks :)
Jarrod

**Comment by edgraham** [comment]
Hi Jarrod,

Could you send me the commands your running and then try running the
example set as such:

'$Binsanity-wf -f . -l igm.fa -c Infant_gut_assembly.cov.x100.lognorm -o
IGM-BinsanityWF 2>standard_error.log'

and then send me the standard error file it outputs, as well as just what
the directory structure looks like when you 'ls' into the output directory.
Then I can send you the commands and such you'll need to work around it!

-Elaina

**Comment by jzrapp** [comment]
Hi @edgraham and @jarrodscott, would you mind sharing your solution for this issue? My Binsanity-lc step Bin clustering step via affinity propagation finished fine, but then my job was terminated because of an checkM install issue. I would like to continue from there.. 
Any help would be appreciated! Thanks!

Josephine
