### ISSUE TITLE
Is it possible to use coverages from other sources ?

### ISSUE THREAD

**Issue by michoug** [edgraham/BinSanity#33]
Hi,
I wanted to know if it was possible to use the coverage results of other tools such as Metabat and it's "jgi_summarize_bam_contig_depths" command instead of the Binsanity-profile command.
Did you already tried it ? Would you advise it ?

Best
Greg

**Comment by edgraham** [comment]
Hi Greg,

It is possible! You just need to ensure the format is the same, e.g that there are no headers and that it’s a tab delimited file. 

The caveat with doing this though is that the preferences we currently have as a default were a general optimum for the log-normalized or scaled coverage profile’s produced in ‘Binsanity-profile’. If your choosing to use the profile from another program It’s likely you’ll have to play around with the preferences. For example if I remember correctly the metabat coverage profile contains the average coverage and the standard deviation of the coverage in each sample. Because these haven’t been normalized in some way the bins you get from Binsanity may not be optimal.

So ultimately, yes you can use other profiles that are in the same format but the preferences may need to be toggled with.

-Elaina

**Comment by michoug** [comment]
Thanks a lot will try that and see how it goes
