### ISSUE TITLE
Binsanity-profile unable to write .cov file

### ISSUE THREAD

**Issue by slambrechts** [edgraham/BinSanity#43]
Hello!

When running 

`Binsanity-profile -i assembly.fasta -s ./ --ids anviocontigs_binsanity.ids -c binsanity -o ./ -T 11 --transform scale`

Everything works fine (bam.saf files, readcounts and readcounts.summary files are all being produced), except for one thing: the binsanity.cov file that gets written is empty. The error message I receive:

```
Traceback (most recent call last):
  File "/usr/local/bin/Binsanity-profile", line 199, in <module>
    make_coverage(args.inputIds, args.outCov, args.outDirectory)
  File "/usr/local/bin/Binsanity-profile", line 70, in make_coverage
    contig_length = cov_data[k].pop(0)
IndexError: pop from empty list
```

Any idea what is going on and how I can fix this?

**Comment by edgraham** [comment]
Hello,

It’s come to my attention that there is a compatibility issue between python 2 and python 3 for the profiling script that I hadn’t initially flagged and I’m in the process of repairing it. So easiest thing to try first is to just run it while specifying python 2.7 as the as the the default python.

If that doesn’t work let me know because then there is another issue at hand.

-Elaina

**Comment by SamLambrechtsUGent** [comment]
Hello,

Thank you for the suggested solution. I tried

`alias python="python2.7"`

followed again by

`Binsanity-profile -i assembly.fasta -s ./ --ids anviocontigs_binsanity.ids -c binsanity -o ./ -T 11 --transform scale`

But the problem seems to persist. I am however no expert and have no idea whether Binsanity-profile was actually using Python 2.7. I did check before and after running Binsanity-profile, by checking `python --version`, and that did return "Python 2.7.13" on both occasions. Not sure if I'm doing this the correct way?

**Comment by edgraham** [comment]
Hello,

First thing, I just put out an update that appears to be fixing this issue on my end (I tested it with someone elses coverage file who was having the same issue). So try updating and see if that remedies it. 

If it does not let me know whether you are using the "Binsanity", "Binsanity-wf",  or "Binsanity-lc" scripts. 

You can also try the following code. Open new python script and copy this into it and name it "fixCov.py" then run it as `python fixCov.py COVERAGEFILE> COVERAGEFILE_Ammended
```
#! /usr/bin/env python
import sys
handle = open(sys.argv[1],"r")
readlines = [filter(None,line.replace("\n","").split(" ")) for line in handle.readlines()]
print '\n'.join(map('\t'.join,readlines))
```

This fixed it for others.
