### ISSUE TITLE
Binsanity-profile speed

### ISSUE THREAD

**Issue by rprops** [edgraham/BinSanity#8]
Hi,

I have a quite large co-assembly that I'd like to run through Binsanity. However, the Binsanity-profile script seems to be incredibly slow. The multiBamCov step is running with babysteps on a node with 30 cores/750Gb RAM available, i.e., in 24 hours the first sample .readcounts file is barely over 1Mb in size.

The (24) SAM files were created with BWA, converted to BAM and sorted with samtools and indexed as well with samtools. For reference, the average BAM file is 8-10 Gb, and its index file 800 - 900 Mb. The co-assembly itself is 13 Gb. I have previously calculated coverage profiles on this co-assembly through bedtools genomecov, and that went rather smooth. 

Do you have any recommendations or insights on why this may be happening?

I'm running samtools v1.3.1 and bedtools2 2.25.

Best,

Ruben

**Comment by edgraham** [comment]
Hi Ruben,

It must be related to the size of the co-assembly because I haven't had issues running it on datasets with large sample sizes and similarly sized BAM files. So first I would look at your assembly, determine what the stats for the 13Gb assembly is. For example, are you filtering out contigs less than 1000bp? 

You can also test using an alternate set of scripts I am working on. There are two scripts in the attached file. One called `get-coverage-featurecount` and another called `combine-readcounts-featurecount`. Note these do use SAM files instead of BAM files right now.
For `get-coverage-featurecount` call it like this (As of right now you will need to do some kind of for loop to cycle through all your samples and generate a readcount file for each of your 24 SAM files)
`get-coverage-featurecount -o sample-name -i fasta-file -s SAM-FILE`
Once you have all 24 readcount files generated use the `combine-readcounts-featurecount` which reads in all `.readcount` files in the current directory and outputs the combined coverage profile. The contig-ids.txt is just a file that has a list of all the contig-ids of interest. For example if your size cutoff is 1000bp you would include all contigs with > 1000bp of length.
`combine-readcounts-featurecount -o name-for-outputfile -i contig-ids.txt`
Thie will produce a `.cov` file. Next you need to transform the data. For this use the `transform-coverage-profile`
`trasnform-coverage-profile -c coverage-file -t scale`

Ultimately this sequence will produce a final file in the order or `file-name.cov.x100.lognorm`

[featurecounts.zip](https://github.com/edgraham/BinSanity/files/664647/featurecounts.zip)

Let me know if this solves the issue!

Regards,
Elaina

**Comment by rprops** [comment]
Hi Elaina,

Thank you for the quick response! No, I didn't in fact remove all contigs <1000bp, because most binning software allows you to do just put a threshold as an extra flag. I'll give your scripts a shot tomorrow and provide you feedback. I do have already a coverage file laying around which is suitable for CONCOCT, maybe I can just use the transform-coverage-profile script to get it normalized appropriately for binsanity.

Thanks again!

Ruben

**Comment by rprops** [comment]
Hi Elaina,

I've tried your new scripts but I'm getting the following error message:
Had both python-anaconda2/201607 and biopython loaded. The script does create a new file but after a certain size it crashes into this error message.
![image](https://cloud.githubusercontent.com/assets/19682548/21447118/b65cacf6-c89d-11e6-91f2-c5eed1fa125d.png)

I'm atm just remapping against the assembly w/o contigs < 1000bp and will try the Binsanity-profile script.

**Comment by edgraham** [comment]
Hi Ruben,

I forgot to specify that this script uses featurecounts instead of bamtools. You'll need to download the package and install it. It is a fairly simple package to get, just download the most recent tarball from the website and configure it. If you don't have Sudo access you can configure it to your user account. I added the link below. 

http://bioinf.wehi.edu.au/subread-package/

Regards,
Elaina Graham

**Comment by rprops** [comment]
Hi Elaina,

I've managed to get Binsanity to work. The only issue is that it is consuming tremendous amounts of RAM (> 1TB) causing the clustering to cancel after a couple of hours. I've tried using only contigs > 3kb, but the clustering again exceeds 1TB of RAM.  As a reference, the binning with concoct on the exact same data consumes less than 60GB, and finishes in approx. 6h on 40 cores/1TB RAM. Do you have any information on memory use by Binsanity, in comparison to other binning software? (Everything runs smoothly on the test data, with a consumption of 60 - 70GB RAM with binsanity-wf)
![image](https://cloud.githubusercontent.com/assets/19682548/21463518/60003986-c938-11e6-929a-a0b1200aa08d.png)

Thanks,

Ruben

**Comment by edgraham** [comment]
Hi Ruben,

Unfortunately that is one of the current known limitations of BinSanity. The nature of the clustering algorithm (Affinity Propagation) is extremely memory intensive. The algorithm produces very accurate results which is why we chose to implement it here rather than another method. We are currently working on options that will reduce he memory complexity without sacrificing the accuracy of the tool.

Regards,
Elaina Graham
